#ifndef __NDM_SRC_CHARSET_8859_1_H__
#define __NDM_SRC_CHARSET_8859_1_H__

/**
 * Automatically generated by @c convgen
 * from @c ./MAPPINGS/ISO8859/8859-1.TXT
 * Range merge code gap is 128.
 * See http://www.unicode.org/Public/MAPPINGS/ for
 * other charsets.
 **/

#include <assert.h>
#include <stddef.h>
#include <stdint.h>

static inline long conv_8859_1_to_uni_(
		const uint8_t *const in,
		const size_t in_bytes,
		uint32_t *cp)
{
	assert (in_bytes > 0);

	*cp = *in;

	return 1;
}

static inline long conv_uni_to_8859_1_(
		uint32_t cp,
		uint8_t *out,
		const size_t out_bytes)
{
	if (out_bytes == 0) {
		return -1;
	}

	if (cp <= 0xff) {
		*out = (uint8_t) cp;

		return 1;
	}

	return 0;
}

#endif /* __NDM_SRC_CHARSET_8859_1_H__ */
